<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container862TD4C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container862TD4C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container862TD4C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container862TD4C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container862TD4C\App_KernelDevDebugContainer([
    'container.build_hash' => '862TD4C',
    'container.build_id' => '8b1ae2c4',
    'container.build_time' => 1615554135,
], __DIR__.\DIRECTORY_SEPARATOR.'Container862TD4C');
