<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKubo6gp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKubo6gp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKubo6gp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKubo6gp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKubo6gp\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kubo6gp',
    'container.build_id' => '1aca748c',
    'container.build_time' => 1615548052,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKubo6gp');
