<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPO9AOIa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPO9AOIa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPO9AOIa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPO9AOIa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPO9AOIa\App_KernelDevDebugContainer([
    'container.build_hash' => 'PO9AOIa',
    'container.build_id' => '08aafa2c',
    'container.build_time' => 1615477434,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPO9AOIa');
