<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL47QkxQ\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL47QkxQ/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerL47QkxQ.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerL47QkxQ\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerL47QkxQ\App_KernelTestDebugContainer([
    'container.build_hash' => 'L47QkxQ',
    'container.build_id' => '12e29243',
    'container.build_time' => 1615303833,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL47QkxQ');
