<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'indexadmin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], []],
    'app_main_main' => [[], ['_controller' => 'App\\Controller\\MainController::main'], [], [['text', '/']], [], []],
    'app_main_blog' => [[], ['_controller' => 'App\\Controller\\MainController::blog'], [], [['text', '/blog']], [], []],
    'app_main_blog_category' => [['category'], ['_controller' => 'App\\Controller\\MainController::blog_category'], [], [['variable', '/', '[^/]++', 'category', true], ['text', '/blog']], [], []],
    'app_main_blog_detail' => [['category', 'id'], ['_controller' => 'App\\Controller\\MainController::blog_detail'], [], [['variable', '/', '[^/]++', 'id', true], ['variable', '/', '[^/]++', 'category', true], ['text', '/blog']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'api_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::apiLogin'], [], [['text', '/api/login']], [], []],
    'api_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::apiLogout'], [], [['text', '/api/logout']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], []],
    'blog' => [[], ['_controller' => 'App\\Controller\\MainController::blog'], [], [['text', '/blog']], [], []],
    'blog_category' => [['category'], ['_controller' => 'App\\Controller\\MainController::blog_category'], [], [['variable', '/', '[^/]++', 'category', true], ['text', '/blog']], [], []],
    'blog_detail' => [['category', 'title'], ['_controller' => 'App\\Controller\\MainController::blog_detail'], [], [['variable', '/', '[^/]++', 'title', true], ['variable', '/', '[^/]++', 'category', true], ['text', '/blog']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'index_admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], []],
    'admin_dashboard' => [[], ['_controller' => 'App\\Controller\\AdminController::admin_dashboard'], [], [['text', '/admin/dashboard']], [], []],
];
