<?php

namespace ContainerL47QkxQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_SecuredAreaService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.config.secured_area' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

        return $container->privates['security.firewall.map.config.secured_area'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('secured_area', 'security.user_checker', '.security.request_matcher.uxbs2bE', true, false, 'security.user.provider.concrete.app_user_provider', 'secured_area', 'security.authentication.basic_entry_point.secured_area', NULL, NULL, [0 => 'http_basic'], NULL);
    }
}
