index:
  path: /
  controller: App\Controller\MainController::index
  methods: GET

blog:
  path: /blog
  controller: App\Controller\MainController::blog
  methods: GET

blog_category:
  path: /blog/{category}
  controller: App\Controller\MainController::blog_category
  methods: GET

blog_detail:
  path: /blog/{category.title}/{blog.title}
  controller: App\Controller\MainController::blog_detail
  methods: GET

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
  methods: GET|POST

index_admin:
  path: /admin
  methods: GET
  controller: App\Controller\AdminController::index

admin_users:
  path: /admin/users
  methods: GET
  controller: App\Controller\AdminController::admin_users

admin_user_create:
  path: /admin/user/create
  methods: GET
  controller: App\Controller\AdminController::admin_user_create

admin_usrs_read:
  path: /admin/user/{id}
  methods: GET
  controller: App\Controller\AdminController::admin_user_read

admin_user_update:
  path: /admin/user/update/{id}
  methods: GET
  controller: App\Controller\AdminController::admin_user_update

admin_user_delete:
  path: /admin/user/delete/{id}
  methods: GET
  controller: App\Controller\AdminController::admin_user_delete

admin_blog:
  path: /admin/blog
  methods: GET
  controller: App\Controller\AdminController::admin_blog

admin_blog_create:
  path: /admin/blog/create
  methods: GET
  controller: App\Controller\AdminController::admin_blog_create

admin_blog_read:
  path: /admin/blog/{id}
  methods: GET
  controller: App\Controller\AdminController::admin_blog_read

admin_blog_update:
  path: /admin/blog/update/{id}
  methods: GET
  controller: App\Controller\AdminController::admin_blog_update

admin_blog_delete:
  path: /admin/blog/delete/{id}
  methods: GET
  controller: App\Controller\AdminController::admin_blog_delete



admin_blog_categories:
  path: /admin/blog/categories
  methods: GET
  controller: App\Controller\AdminController::admin_blog_categories

admin_blog_categories_create:
  path: /admin/blog/categories/create
  methods: GET
  controller: App\Controller\AdminController::admin_blog_categories_create

admin_blog_categories_read:
  path: /admin/blog/categories/{id}
  methods: GET
  controller: App\Controller\AdminController::admin_blog_categories_read

admin_blog_categories_update:
  path: /admin/blog/categories/update/{id}
  methods: GET
  controller: App\Controller\AdminController::admin_blog_categories_update

admin_blog_categories_delete:
  path: /admin/blog/categories/delete/{id}
  methods: GET
  controller: App\Controller\AdminController::admin_blog_categories_delete
